import { FATCH_ACTION_PREFIX, DOWNLOAD_ACTION_PREFIX } from 'utils/constants';
import NAMESPACE from './namespace';

export const GET_CITY_LIST = `${FATCH_ACTION_PREFIX}GET_CITY_LIST_${NAMESPACE}`;

// 消息管理
export const GET_ORDER_LIST = `${FATCH_ACTION_PREFIX}GET_ORDER_LIST_${NAMESPACE}`;
export const GET_ORDER_CONFIG = `${FATCH_ACTION_PREFIX}GET_ORDER_CONFIG${NAMESPACE}`;
export const UPDATE_SEARCH_CONDITION = `UPDATE_SEARCH_CONDITION_${NAMESPACE}`;
export const UPDATE_ORDER_CONFIG_MAP = `UPDATE_ORDER_CONFIG_MAP${NAMESPACE}`;
export const DOWNLOAD_ORDER_LIST = `${DOWNLOAD_ACTION_PREFIX}DOWNLOAD_ORDER_LIST${NAMESPACE}`;
